### ISSUE TITLE
Issue in Longstring function

### ISSUE THREAD

**Issue by GauravRohilla605** [Cameron-Lyons/careless#1]
Hello Cameron,

I am trying to implement longstring function on a panda df.
but its throwing an error.
Can you add a sample run for longstring function

**Comment by GauravRohilla605** [comment]
for the following string

11431155114411331133113511122211115511342133

output should be 4 but the function is giving 2

**Comment by Cameron-Lyons** [comment]
Fixed it will now return a tuple with the correct character and length
